# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fdc28ea0a8272cf471b151b7abcf9677e7dfd3e66fcd36370056c039fbe926400e5baa034d1b2b98006fc58fe0160c2c930b5c59bb8d43a1770cc39b70a19d7

test:
  secret_key_base: bb1bc8359f3a986b115d3691e7d9e0d48df07fcf48d51af277380915951256fe7bd1599dcd6530f2556f4b28d1d40d976f3b8e0775095786c49d2e63fbc187b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
